ConfigKey: configkey
Serilog:
  MinimumLevel:
    Default: Information
    Override:
      Microsoft: Warning
      System: Warning
  WriteTo:
    - Name: File
      Args:
        path: 'C:/SAFRA/Wheather_.log'
        rollingInterval: Day
        outputTemplate: >-
          {Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u3}]
          {Message:lj}{NewLine}{Exception}
        shared: true
  Enrich:
    - FromLogContext
Logging:
  LogLevel:
    Default: Information
    Microsoft: Warning
    Microsoft.Hosting.Lifetime: Information
version: Corporate ACtion Version YML DEV version 1.1
ServerConnection:
  Url: localhost
  Port: '8080'
  IsSSL: 'false'
  Password: HostPassword
ConnectionStrings:
  DefaultConnection: >-
    Data Source=JACOB_LAPTOP\MSSQLSERVER01;Initial
    Catalog=CorporateActions;Integrated Security=True;Encrypt=False
  OlDefaultConnection: >-
    JACOB_LAPTOP;Initial
    Catalog=CorporateActions;trusted_connection=true;MultipleActiveResultSets=true
  CADBConnectionString: >-
    Data Source=JACOB_LAPTOP;Initial Catalog=CorporateActions;User
    ID=cadb;Password=cadb;Integrated
    Security=True;Pooling=False;MultipleActiveResultSets=true
  ExcelOleDBConnectionString: >-
    Provider=Microsoft.ACE.OLEDB.12.0;Data Source={0};Extended
    Properties=";Excel 8.0;HDR=YES&quot;
MainPath:
  MainExecPath: 'c:/SAFRA'
  MainDataPath: 'c:/SAFRA/Swift Data'
IncomingSwiftFile:
  ExecutableArguments: '{0}'
  ExecutableFile: Process_Swift_incoming_file.bat
  ExecutablePath: 'C:/SAFRA/Corporate Actions'
  FolderDescription: Incoming Swift Message Data Folder
  FolderEnabled: true
  FileFilter: '*.*'
  FolderIncludeSub: false
  FolderPath: 'C:/SAFRA/Corporate Actions/Data/IncomingMt564'
  FileProcessingFolder: 'c:/SAFRA/Processing'
  FileArchiveFolder: 'C:/SAFRA/Corporate Actions/Archive'
  FileErrorFolder: 'C:/SAFRA/Corporate Actions/Errors'
  IntervalInMinutes: 5
  MultiMessageSeparator:
    - $
    - '|'
TraceParameters:
  WithTrace: false
  TraceFileName: 'SwiftTracing_{yyyyMMdd}.txt'
  TraceFolder: 'C:/SAFRA/Corporate Actions/Logs'
